config/routes.rb
Rails.application.routes.draw do
  resources :sales

  root 'sales#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
	validates :book, :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all

    @total = 0
    @sales.each do |s|
      @total+= s.price
    end
    @total
  end

  # GET /sales/1
  # GET /sales/1.json
  def show

  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:book, :price, :total, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Livraria</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@sale.errors.count, "error") %> was found:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book %><br>
    <%= f.text_field :book %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
    <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<div class="container-fluid">
<div class="panel panel-primary">
  <div class="panel-heading"> <h1>Listing sales</h1> </div>
    <div class="panel-body">

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Image</th>
          <th>Book</th>
          <th>Price</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @sales.each do |sale| %>
          <tr>
            <td><%= image_tag(sale.image_url, height: '100', width: '70') %></td>
            <td><%= sale.book %></td>
            <td><%= sale.price %></td>
            <td><%= link_to 'Show', sale %></td>
            <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
            <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
          <tr>
            <td> <b> Total</b> </td>
            <td> <b> <%= @total %> </b> </td>
          </tr>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Sale', new_sale_path %>
    </div>
  </div>
</div>

app/views/sales/new.html.erb
<div class="container-fluid">
	<div class="panel panel-primary">
  		<div class="panel-heading"> <h1>New sale</h1></div>
    		<div class="panel-body">

					<%= render 'form' %>

					<%= link_to 'Back', sales_path %>
			</div>
	</div>
</div>

app/views/sales/show.html.erb
<div class="container-fluid">
	<div class="panel panel-primary">
  		<div class="panel-heading"> <h1>New sale</h1></div>
    		<div class="panel-body">
				<p id="notice"><%= notice %></p>

				<p>
				  <strong>Book:</strong>
				  <%= @sale.book %>
				</p>

				<p>
				  <strong>Price:</strong>
				  <%= @sale.price %>
				</p>

				<p>
				  <strong>Image url:</strong>
				  <%= image_tag(@sale.image_url) %>
				</p>


				<%= link_to 'Edit', edit_sale_path(@sale) %> |
				<%= link_to 'Back', sales_path %>
		</div>
	</div>
</div>